version: '3.8'

services:
  # 1. Database chính
  postgres-app:
    image: postgres:16-alpine
    container_name: foxtrip-postgres
    environment:
      POSTGRES_DB: foxtrip
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - foxtrip-network

  # 2. Database riêng cho Keycloak
  postgres-keycloak:
    image: postgres:16-alpine
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - foxtrip-network

  # 3. Keycloak Server (Identity Provider)
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: foxtrip-keycloak
    command: start-dev --features=token-exchange,admin-fine-grained-authz
    environment:
      # Trỏ vào container postgres-keycloak ở trên
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Cho phép truy cập qua mạng nội bộ Docker
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres-keycloak
    networks:
      - foxtrip-network

  # 4. MongoDB
  mongodb:
    image: mongo:7-jammy
    container_name: foxtrip-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: foxtrip
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - foxtrip-network

  # 5. Redis Cache
  redis:
    image: redis:7-alpine
    container_name: foxtrip-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - foxtrip-network

  # 6. MailHog (Test gửi mail)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: foxtrip-mailhog
    ports:
      - "1025:1025"  # SMTP Port (Cấu hình trong Spring Boot)
      - "8025:8025"  # Web UI (Vào trình duyệt xem mail)
    networks:
      - foxtrip-network

volumes:
  postgres_data:
  keycloak_db_data: # Volume mới cho DB Keycloak
  mongodb_data:
  redis_data:

networks:
  foxtrip-network:
    driver: bridge